# Site
repository: jiyang91/jiyang91.github.io
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Jiyang Lee
title: Mechatronics Engineer
email: jiyang.lee91@gmail.com
website: https://jiyang91.github.io
CV:
# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username: jiyang91
googlescholar_username: PWN7rLIAAAAJ
youtube_username: UC1j9IwcZfdZPYXOFNxQwHow
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jylee
# linkedin_username: jylee
# xing_username: jekyll
# pinterest_username: jekyll
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Google Analytics and Tag Manager
gtag: "G-2YPRTHGBR2"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/jylee.jpg
about_content: | # this will include new lines to allow paragraphs
  I am Jiyang Lee from South Korea. I am a Research Engineer in LG Display, Vision Inspection Team, doing research on computer vision algorithms in display manufacturing fields.

  I worked at KIST(Korea Institute of Science and Technology), developing a skewed-legged quadruped robot, and CSCAM, designing semiconductor machienes and anomaly detection program for Cell-Phone Frame.

  Previously, I completed my master work on Developing Computer vision based path planning robotic system, CAD/CAM lab in Sogang University, Seoul, working in the group headed by Cheol-Soo Lee. I published <a href="https://www.tandfonline.com/doi/abs/10.1080/0951192X.2018.1429669">Path planning for SCARA robot based on marker detection using feature extraction and, labelling.</a>


  - Technical Skills

      - Programming: <mark>C++</mark>, <mark>Python</mark>, <mark>C#</mark>, <mark>OpenCV</mark>, <mark>PyTorch</mark>, and <mark>Cuda</mark>

      - Mechanical Design: <mark>Autodesk AutoCAD</mark>, <mark>Inventor</mark>, and <mark>SolidWorks</mark>

      - Languages: Korean, English

content:
  - title: Projects
    layout: list
    content:
      - layout: top-middle
        border: weak
        title: Robotic PET dispensing
        sub_title:
        caption: Jan. 2015. - Feb. 2017.
        description: |
          What I contributed: My project in master course was Developing Automated PET Dispenser. The main objective of this work is developing the production system for radioactive products using the SCARA robot. It help protecting workers from exposing to radioactive.

          Review: This project taught me a lot. C++ MFC was the language all I could use, and I should control and communicate with robots and

      - layout: top-middle
        title: Few-shot learning
        sub_title:
        caption: Feb. 2022. - Jun. 2022.
        border: weak
        description: |
          What I contributed: I tried to build classification model for Fine Metal Mask(FMM). Dataset(6-classes) has some issues: Human-error, imbalanced dataset. Initially, I tried to use Resnet with Mixup augmentation. The result was 40% Accuracy. To improve the accuracy, I removed meaningless classes and tried to use Few-shot learning(MAML, ProtoNet, ProtoMAML). The result improved to about 80% accuracy with 4 classes.

          Review

      - layout: top-middle
        title: Anomaly Detection
        sub_title:
        caption: Oct. 2021. - Present
        border: weak
        description: |
          What I contributed: I developed anomaly detection system using Padim(<a href="https://arxiv.org/abs/2011.08785">Patch Distribution Modeling Framework for Anomaly Detection and Localization<a/>).

          Review: aaaa

      - layout: top-middle
        border: weak
        title: Quadruped robot
        caption: Oct. 2018. - Feb. 2020.
        sub_title:
        description: |

          - What I contributed

          I developed quadruped robot with 12 smart motors(<a href="https://www.robotis.com/shop/list.php?ca_id=203010">Robotis H54P motors<a/>). During designing, I was focused on compatibility between modules. In final model, most of parts are compatible except main plates. I completly assembled quadruped robot and experimented simple angular motions in static state. In addition, installing camera module on robot and experimented it's status.

          - Review

          It was my first mobile robot project. I learned how to build them.

          - Image

          ![alt text](./images/Quadrupedrobot.png "Trees")

  - title: Education
    layout: list
    border: weak
    content:
      - layout: left
        border: weak
        title: Sogang University
        sub_title: Master of Science in Mechanical Engineering
        caption: Mar. 2015 - Feb. 2017
        description: |
          - Master Thesis: Development of Path Planning using Marker for SCARA Robot PET Dispensing System 
            <br/>(*Advisor: Prof. Cheol-soo Lee*)
          - Graduate Research Assistant, <a ref="http://cadcam.sogang.ac.kr/index.php">CAD/CAM Lab</a>
            - Analyzed PET Dispensing system, and Composed robotic dispensing system.
          - Designed various multi-axis manipulators, especially made SCARA robot for industrial purpose.
          - Published two journals; attended three conferences.
      - layout: left
        border: weak
        sub_title: Bachelor of Science in Mechanical Engineering
        caption: Mar. 2011 - Feb. 2015
        description: |
          -	Admitted with highest distinction in Korean SAT and scholarship
          -	Scholarship for an Excellent Record for 2 years (Full tuition, Merit-based scholarship)
          -	Xavier Scholarship for one year (Half tuition, Merit-based scholarship)

  - title: Publication
    layout: text
    content: |
      - Journals
        1.	Lee, J.Y. and Lee, C.S. (2018). Path planning for SCARA robot based on marker detection using feature extraction and labelling. International Journal of Computer Integrated Manufacturing, 31(8), 769-776.   <a href="https://www.tandfonline.com/doi/abs/10.1080/0951192X.2018.1429669">[link]<a/>
        2.	Lee, J.Y., Lee, D.G., and Lee, C.S. (2017). Development of Robotic Dispensing System for Radiopharmaceuticals using SCARA Robot. Journal of the Korean Society of Manufacturing Technology Engineers, 26(5), 441-449. [Best Paper Award]   <a href="https://www.dbpia.co.kr/Journal/articleDetail?nodeId=NODE07256079">[link]<a/>
        

      - Conferences
        3.	Kim, M., Lee, J.Y., Kim, J., Nigatu, H., and Kim, D. A Robust Position Estimation Algorithm under Unusual Large Range Errors, 2019 28th IEEE International Conference on Robot and Human Interactive Communication (ROMAN), New Delhi, India, 2019, pp. 1-6 (Oral session).   <a href="https://www.researchgate.net/profile/Hassen_Nigatu/publication/338588210_A_Robust_Position_Estimation_Algorithm_under_Unusual_Large_Range_Errors/links/60ab49f8299bf1031fc43005/A-Robust-Position-Estimation-Algorithm-under-Unusual-Large-Range-Errors.pdf">[link]<a/>
        4.	Lee, J.Y. and Lee, C.S., Path planning for SCARA robot based on marker detection using feature extraction, labeling, and inverse perspective transform. 26th International Conference on Flexible Automation and Intelligent Manufacturing, Seoul, Korea, Jun. 2016 (Presenter, Oral session).
        5.	Lee, C.S., Lee, J.Y., Lee, D.G. and Kim, J.M. Teleoperation of SCARA Robot for Radiopharmaceutical Product Dispensing. 2016 Fall Conference of The Korean Society of Manufacturing Technology Engineers, Jeju Island, Korea, Nov. 2016 (Oral session).   <a href="https://www.dbpia.co.kr/Journal/articleDetail?nodeId=NODE07059326">[link]<a/>
        6.	Lee, J.Y. and Lee, C.S. SCARA Robot 2-Dimensional Path Planning by Using Markers. The 2016 Winter Conference of Society for Computational Design and Engineering, Gangwon Province, Korea, Jan. 2016 (Presenter, Oral session).   <a href="https://www.dbpia.co.kr/Journal/articleDetail?nodeId=NODE06648627">[link]<a/>

  - title: Experience
    layout: list
    content:
      - layout: left
        border: weak
        title: LG Display
        sub_title: Vision Inspection Algoirthm Team<br><i>Research engineer</i>
        caption: Dec. 2020 - Present
        description: |
          -	Develop a Multi-anomaly Detection Tool for user-friendly interface to train and test different models.
              -	Design a GUI interface to support individual SOTA anomaly detection methods.
              -	Deploy different anomaly detection strategy in one interface and optimize each method.

          -	Constructed an anomaly detection system for stain defect on display panels.
              -	Main Issues: Undifferentiable stain defect on display panel; non-automated alarming system for manufacturing line. 
              -	Built an automatic anomaly detection and localization system for stain defect. 
              -	Established a real-time auto-mailing system to send detection results and alarms to the production line. 

          -	Developed a Few-Shot Learning Classification Model for defect images in Fine Metal Mask (FMM).
              -	Main Issues: Tiny defect detection problem, small dataset training, and data imbalance.
              -	Improved the current detection rate by 16% and optimized data augmentation for the classification system.

          -	Accelerated the legacy system with a CUDA-based algorithm; transformed CPU functions to GPU kernels to save time.
              -	Upgraded two major algorithms used in a smart factory and increased the speed by seven times.

      - layout: left
        border: weak
        title: Korea Institute of Science and Technology
        sub_title: Robot and media institute<br><i>Research engineer</i>
        caption: Oct. 2018 - Feb. 2020
        description: |
          -	Designed and assembled a quadruped robot with smart motors; programmed position control program with inverse dynamics.

          -	Developed a remote 360-degree panoramic view system for the command centers of Firefighting Armored Robots.
              -	Upgraded the wired system to WI-FI 6 wireless panoramic view system to support firefighters in disaster rescue vehicles.
              -	Demonstrated multi-robots (armored robot, drones, and snake robot) with a firefighter team in disaster simulations.

          -	Estimated positions for a robot swarm with various type of sensors in an indoor environment.
              -	Conducted an experiment on an Ultra-wideband (UBW) sensor-based algorithm with five TurtleBots.
              -	Published one conference paper (3).

      - layout: left
        border: weak
        title: CSCAM
        sub_title: CNC Department<br><i>Assistant Research Engineer</i>
        caption: Jan. 2017 - Sep. 2018
        description: |
          -	Devised a Smartphone aluminum frame vision (optic/mechanical) inspection machine in two stages to identify surface defects. 
              -	Programmed the software and implemented a rule-based algorithm with OpenCV to create an optimal inspection setting.

          -	(Client: Samsung Electro-Mechanics) Designed mechanisms and components to build a high-precision, high-stability XRF inspection machine using Autodesk Inventor; created and managed BOM list.

          -	(Client: Samsung Display) Constructed a loading machine and buffer machine in the T-bending manufacturing line for OLED; modified parts designs and diagrams, and created and managed BOM list.

# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag

exclude:
  [
    "Gemfile",
    "Gemfile.lock",
    "node_modules",
    "vendor/bundle/",
    "vendor/cache/",
    "vendor/gems/",
    "vendor/ruby/",
    "lib/",
    "scripts/",
    "docker-compose.yml",
  ]
